# -*- coding: utf-8 -*-
"""01_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kIGkOn5k4y87_hNVwd3znw8BZWKkzO7F

# 01 – Exploratory Data Analysis (EDA)

This notebook loads the German Credit dataset, assigns column names, and performs initial exploratory checks.
It establishes the foundation for preprocessing, modeling, and evaluation in later notebooks.

## Load the libraries
"""

# Import required libraries
import pandas as pd
import numpy as np

"""## Load the German Credit Datset"""

# Load the Datset from GitHub
url = "https://raw.githubusercontent.com/KrisAimlGitHub/credit-risk-capstone/main/data/raw/german.data"
df = pd.read_csv(url, sep=' ', header=None)

print('Dataset loaded. Shape: ', df.shape)
print('\n')
print('Dataset head:')
df.head()

"""## Assign Column Names

The German Credit dataset contains 20 features and 1 target variable.
"""

# Assign the Column Names
columns = [
    'checking_status',  'duration',   'credit_history',   'purpose',                 'credit_amount',
    'savings',          'employment', 'installment_rate', 'personal_status',         'other_debtors',
    'residence_since',  'property',   'age',              'other_installment_plans', 'housing',
    'existing_credits', 'job',        'dependents',       'telephone',               'foreign_worker',
    'target'
]

df.columns = columns

df.head()

"""## Basic Visual Inspection of Dataset

We check the structure, data types, summary statistics, and class distribution.
"""

# Check for Null Values

if(df.isnull().sum().sum() == 0):
    print('No Null Values Found')
else:
    print('Null Values Found. Let us explore further')

# Print Column Information
df.info()

# Statestics Summary
df.describe(include='all')

# Print Distribution of Target
df['target'].value_counts()

"""## Summary on EDA

- The dataset contains 1,000 rows and 21 columns.
- Most variables are categorical and require encoding.
- The target variable is imbalanced (typically ~70% good, ~30% bad).
- No missing values are present in the raw dataset.
- Numeric variables such as `duration`, `credit_amount`, and `age` will require scaling for certain models.

With these insights, let's proceed with preprocessing steps in the next notebook (02_preprocessing.ipynb).

Note: Detailed discussion on the observations will be presented in the report.
"""