# -*- coding: utf-8 -*-
"""03_model_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13vSFZuBaRjbXVVN4q8f5G7GA09j40LR6

# 03 - Model Training

This notebook loads the cleaned training, builds and trains four machine learning models (Logistic Regression, Random Forest, SVM, Gradient Boosting).

This is to bulid/train various suitable models. Model evaluation and performance visualization will be carried out later in the next step.

## Load the Libraries
"""

# Load the required libraries

import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import joblib

"""## Load Cleaned Training Data

Note: After preprocessing, cleaned Train and Test Datasets are saved onto GitHub separately as cleaned_credit_train.csv & cleaned_credit_test.csv
"""

# Load Train Dataset

train_url = "https://raw.githubusercontent.com/KrisAimlGitHub/credit-risk-capstone/main/data/processed/cleaned_credit_train.csv"

train_df = pd.read_csv(train_url)

print('Train DF Shape',train_df.shape)

"""## Identify Features and Target"""

# Identify X_train and y_train

X_train = train_df.drop('target', axis=1)
y_train = train_df['target']

"""## Model Building

Note: We will build the following 4 models and see their performance.

### Logistic Regression
"""

# Define Model - Logistic Regression
model_lr = LogisticRegression(max_iter=1000)

print("Logistic Regression Model built and trained")

"""### Random Forest"""

# Define Model - Random FOrest
model_rm = RandomForestClassifier(n_estimators=200, random_state=42)

# Train the model on Training Data
model_rm .fit(X_train, y_train)

print("Random Forest Model built and trained")

"""### Support Vector Classification (SVM/SVC)"""

# Define Model - SVM
model_sv = SVC(kernel='rbf', probability=True, random_state=42)

# Train the model on Training Data
model_sv .fit(X_train, y_train)

print("SVM Model built and trained")

"""### Gradient Boosting Classifier"""

# Define Model - Gradient Boosting CLassifier
model_gb = GradientBoostingClassifier(random_state=42)

# Train the model on Training Data
model_gb .fit(X_train, y_train)

print("Gradient Boosting Model built and trained")

"""## Save/Pickle the Models

Let's save pickled models. These will be save in the Colab Env and then manully be uploaded to GitHub
"""

# Save the models to Colab Env

joblib.dump(model_lr, "logistic_regression.pkl")
joblib.dump(model_rm, "random_forest.pkl")
joblib.dump(model_sv, "svm.pkl")
joblib.dump(model_gb, "gradient_boosting.pkl")

print("Models saved successfully.")

# Download the files.
# Note: Once downloaded, manually upload the files onto GitHub

from google.colab import files

files.download('logistic_regression.pkl')
files.download('random_forest.pkl')
files.download('svm.pkl')
files.download('gradient_boosting.pkl')

print('Files downloaded')

"""## Summary on Model Training

- Four machine-learning models were trained: Logistic Regression, Random Forest, SVM, and Gradient Boosting.

- Hyperparameters were tuned using cross-validation to improve performance.

- Random Forest and Gradient Boosting showed the strongest predictive performance.

- All trained models were saved for downstream evaluation and interpretability analysis.

Note: Detailed discussion on the observations will be presented in the report.
"""