# -*- coding: utf-8 -*-
"""05_shap_interpretability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-zzqzQSga3C5Ymf-GElbxAE-pg-PnhoK

# 05 - SHAP Interpretability

This notebook uses SHAP (SHapley Additive exPlanations) to interpret the predictions of the machine learning model trained for credit-default prediction. It supports Research Question 1 (key predictors) and Research Question 3 (interpretability).

## Load the Libraries
"""

# Load the required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib

"""## Install and Import SHAP"""

# Install and Load Shap

!pip install shap
import shap

"""## Load Cleaned Test Data"""

test_url = "https://raw.githubusercontent.com/KrisAimlGitHub/credit-risk-capstone/main/data/processed/cleaned_credit_test.csv"
test_df = pd.read_csv(test_url)

X_test = test_df.drop('target', axis=1)
y_test = test_df['target']

"""## Load the Trained Model from GitHub

You can choose which model to interpret:
- Random Forest (recommended for interpretability)
- Gradient Boosting

"""

# Load the model from GitHub

import urllib.request

# Choose the model you want to interpret
model_filename = "random_forest.pkl"

base_url = "https://raw.githubusercontent.com/KrisAimlGitHub/credit-risk-capstone/main/models/"
url = base_url + model_filename

# Download model locally
urllib.request.urlretrieve(url, model_filename)

# Load model
model = joblib.load(model_filename)
print(f"Loaded model: {model_filename}")

"""## Initialize SHAP Explainer"""

explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_test)

"""## SHAP Summary Plot (Global Feature Importance)

This plot shows which features contribute most to the model's predictions.
"""

shap.summary_plot(shap_values, X_test, plot_type="dot")

"""## SHAP Bar Plot (Mean Absolute SHAP Values)"""

shap.summary_plot(shap_values[:, :, 1], X_test, plot_type="bar")

"""## SHAP Dependence Plots for Top Features

These plots show how each feature influences predictions.
"""

top_features = X_test.columns[:6]  # or manually choose based on summary plot

for feature in top_features:
    shap.dependence_plot(feature, shap_values[:, :, 1], X_test)



"""## SHAP Force Plot for a Single Prediction"""

# Display force plot for the first test sample for the positive class (index 1)
shap.initjs()
shap.force_plot(explainer.expected_value[1], shap_values[0, :, 1], X_test.iloc[0])

"""## Summary on SHAP Interpretability

- SHAP was used to interpret the Random Forest model’s predictions.

- Global SHAP summary plots identified key drivers of credit risk, including credit amount, duration, checking account status, and credit history.

- SHAP dependence plots highlighted how feature values influence prediction outcomes.

- Local explanations (force plots) demonstrated how individual predictions are formed.

- These insights improve transparency and support responsible model deployment.

Note: Detailed discussion on the observations will be presented in the report.
"""